apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: {{ .Values.services.redis.container_name }}
          image: {{ .Values.services.redis.container_image }}
          ports:
            - containerPort: {{ .Values.services.redis.container_port }}
              protocol: {{ .Values.services.redis.container_protocol }}