apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: ws5
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: 'redis:alpine'
          ports:
            - containerPort: 6379
              protocol: TCP


---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ws5
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379